### ISSUE TITLE
Mismatched numbering 

### ISSUE THREAD

**Issue by Addy81** [eastgenomics/eggd_generate_workbook#57]
It seems that running reanalysis produces mismatched number reports. 

For example today we run a reanalysis:
dias.py -a TWE reanalysis /output/dias_single_v1.2.2-TWE_v1.0.4-210828-1/ X217983_RA

Which yielded X217983_1.xls and X217983_2_coverage_report.xls.

I assume it has to do with the removal of the additional sample information from the Sample ID?

Link to job: https://platform.dnanexus.com/projects/G4b2PJj4fyv532vYF3kVzx0f/monitor/analysis/G65q9G04fyvB79094Pjj6YVq

**Comment by Yu-jinKim** [comment]
So we have this reanalysis workflow ran in August: https://platform.dnanexus.com/projects/G4b2PJj4fyv532vYF3kVzx0f/monitor/analysis/G4g4XKQ4fyv83zxK0y1jPZvQ which outputted a X + GM xls report while the Athena reports were just named X.
Dias v1.8.1 won't have this issue in the future as the reports will only be X.
So I'm not sure if that is something that we want to try and fix it. I'll bring it up during the Dias meeting
